/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.16.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;


#nullable disable                // suppress C# 8.0 nullable contexts (we still support earlier versions)
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

public static class clientExtensions
{
  public static bool Equals(this List<Child> instance, object that)
  {
    if (!(that is List<Child> other)) return false;
    if (ReferenceEquals(instance, other)) return true;

    return TCollections.Equals(instance, other);
  }


  public static int GetHashCode(this List<Child> instance)
  {
    return TCollections.GetHashCode(instance);
  }


  public static List<Child> DeepCopy(this List<Child> source)
  {
    if (source == null)
      return null;

    var tmp253 = new List<Child>(source.Count);
    foreach (var elem in source)
      tmp253.Add((elem != null) ? elem.DeepCopy() : null);
    return tmp253;
  }


  public static bool Equals(this List<Round> instance, object that)
  {
    if (!(that is List<Round> other)) return false;
    if (ReferenceEquals(instance, other)) return true;

    return TCollections.Equals(instance, other);
  }


  public static int GetHashCode(this List<Round> instance)
  {
    return TCollections.GetHashCode(instance);
  }


  public static List<Round> DeepCopy(this List<Round> source)
  {
    if (source == null)
      return null;

    var tmp254 = new List<Round>(source.Count);
    foreach (var elem in source)
      tmp254.Add((elem != null) ? elem.DeepCopy() : null);
    return tmp254;
  }


}
