/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace CompetitionClient
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Child : TBase
  {

    public long Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int Age { get; set; }

    public bool IsNull { get; set; }

    public Child() {
      this.IsNull = false;
    }

    public Child(long id, string firstName, string lastName, int age, bool isNull) : this() {
      this.Id = id;
      this.FirstName = firstName;
      this.LastName = lastName;
      this.Age = age;
      this.IsNull = isNull;
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_id = false;
        bool isset_firstName = false;
        bool isset_lastName = false;
        bool isset_age = false;
        bool isset_isNull = false;
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I64) {
                Id = iprot.ReadI64();
                isset_id = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                FirstName = iprot.ReadString();
                isset_firstName = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.String) {
                LastName = iprot.ReadString();
                isset_lastName = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.I32) {
                Age = iprot.ReadI32();
                isset_age = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.Bool) {
                IsNull = iprot.ReadBool();
                isset_isNull = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
        if (!isset_id)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Id not set");
        if (!isset_firstName)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field FirstName not set");
        if (!isset_lastName)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field LastName not set");
        if (!isset_age)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Age not set");
        if (!isset_isNull)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field IsNull not set");
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("Child");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        field.Name = "id";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(Id);
        oprot.WriteFieldEnd();
        if (FirstName == null)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field FirstName not set");
        field.Name = "firstName";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(FirstName);
        oprot.WriteFieldEnd();
        if (LastName == null)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field LastName not set");
        field.Name = "lastName";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(LastName);
        oprot.WriteFieldEnd();
        field.Name = "age";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Age);
        oprot.WriteFieldEnd();
        field.Name = "isNull";
        field.Type = TType.Bool;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(IsNull);
        oprot.WriteFieldEnd();
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("Child(");
      __sb.Append(", Id: ");
      __sb.Append(Id);
      __sb.Append(", FirstName: ");
      __sb.Append(FirstName);
      __sb.Append(", LastName: ");
      __sb.Append(LastName);
      __sb.Append(", Age: ");
      __sb.Append(Age);
      __sb.Append(", IsNull: ");
      __sb.Append(IsNull);
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
