--Dirty Reads 2
SET TRANSACTION ISOLATION LEVEL READ
UNCOMMITTED
BEGIN TRAN
SELECT * FROM Angajati
INSERT INTO LogTable VALUES('select','Angajati',CURRENT_TIMESTAMP)
WAITFOR DELAY '00:00:15'
SELECT * FROM Angajati
INSERT INTO LogTable VALUES('select','Angajati',CURRENT_TIMESTAMP)
COMMIT TRAN

--Dirty Reads SOLUTION
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM Angajati
INSERT INTO LogTable VALUES('select','Angajati',CURRENT_TIMESTAMP)
WAITFOR DELAY '00:00:15'
SELECT * FROM Angajati
INSERT INTO LogTable VALUES('select','Angajati',CURRENT_TIMESTAMP)
COMMIT TRAN


-- Non repeatable 2
SET TRANSACTION ISOLATION LEVEL READ
COMMITTED
BEGIN TRAN
SELECT * FROM Angajati
INSERT INTO LogTable VALUES('select','Angajati',CURRENT_TIMESTAMP)
WAITFOR DELAY '00:00:15'
SELECT * FROM Angajati
INSERT INTO LogTable VALUES('select','Angajati',CURRENT_TIMESTAMP)
COMMIT TRAN

-- Non repeatable SOLUTION
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM Angajati
INSERT INTO LogTable VALUES('select','Angajati',CURRENT_TIMESTAMP)
WAITFOR DELAY '00:00:15'
SELECT * FROM Angajati
INSERT INTO LogTable VALUES('select','Angajati',CURRENT_TIMESTAMP)
COMMIT TRAN

--Phantom Reads 2
SET TRANSACTION ISOLATION LEVEL REPEATABLE
READ
BEGIN TRAN
SELECT * FROM Angajati
INSERT INTO LogTable VALUES('select','Angajati',CURRENT_TIMESTAMP)
WAITFOR DELAY '00:00:15'
SELECT * FROM Angajati
INSERT INTO LogTable VALUES('select','Angajati',CURRENT_TIMESTAMP)
COMMIT TRAN

-- Phantom reads SOLUTION
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
SELECT * FROM Angajati
INSERT INTO LogTable VALUES('select','Angajati',CURRENT_TIMESTAMP)
WAITFOR DELAY '00:00:15'
SELECT * FROM Angajati
INSERT INTO LogTable VALUES('select','Angajati',CURRENT_TIMESTAMP)
COMMIT TRAN


-- Deadlock 2
BEGIN TRAN
UPDATE Inchirieri SET status_inchiriere='in curs' WHERE id_inchiriere=1
INSERT INTO LogTable VALUES('update','Proiecte',CURRENT_TIMESTAMP)
WAITFOR DELAY '00:00:10'

UPDATE Angajati SET nume_angajat='Eminescu' WHERE id_angajat =3
INSERT INTO LogTable VALUES('update','Angajati',CURRENT_TIMESTAMP)
COMMIT TRAN

-- Deadlock SOLUTION
SET DEADLOCK_PRIORITY HIGH
BEGIN TRAN
UPDATE Inchirieri SET status_inchiriere='in curs' WHERE id_inchiriere=1
INSERT INTO LogTable VALUES('update','Inchirieri',CURRENT_TIMESTAMP)
WAITFOR DELAY '00:00:15'

UPDATE Angajati SET nume_angajat='Eminescu' WHERE id_angajat =3
INSERT INTO LogTable VALUES('update','Angajati',CURRENT_TIMESTAMP)
COMMIT TRAN