( defun exemplul_1 ()
  ( setq a 19 )
  ( setq b 22 )
  ( + 22 ( * a ( + 13 b ) ) )
  )
( defun exemplul_2 ()
  ( setq a 2 )
  ( setq b 2 )
  ( setq c 2 )
  ( setq d 2 )
  ( + (* a b ) (* c d ) )
  )


( defun deg2rad ( deg / rad )
  ( setq rad ( * deg pi) )
  ( / rad 180 )
  )
( defun rad2deg ( rad / deg )
  ( setq deg ( * rad 180 ) )
  ( setq deg ( / deg pi ) )
  ( fix deg )
  )