package rpcprotocol;

public enum ResponseType {
    OK, ERROR,LOGIN,FIND_ALL_USERS,FIND_ALL_BUGS,FIND_ALL_BUGS_PROGRAMMER,REPAIR_BUG,
    SAVE_BUG, UPDATE, SAVE_USER,DELETE_USER,UPDATE_USER,UPDATE_BUG,DELETE_BUG,FIND_ALL_STEPS_BUG,SAVE_STEP,UPDATE_STEP,DELETE_STEP
}